#!/usr/bin/env bash
set -euo pipefail
# Generate .env files for services from Terraform outputs.
# Requires: terraform installed and applied for relevant stacks.

ROOT_DIR=$(cd "$(dirname "$0")/.." && pwd)

function output_json() {
  local dir=$1
  terraform -chdir="$dir" output -json
}

# Example: write ML env using cloud_storage + bigquery outputs
ML_ENV="$ROOT_DIR/../ml/.env.generated"
{
  echo "# Generated by infra/scripts/generate_env.sh"
  echo "GCP_PROJECT_ID=${GCP_PROJECT_ID:-comoda}"
  echo "GCS_BUCKET=${GCS_BUCKET:-comoda-models}"
  echo "BQ_DATASET=${BQ_DATASET:-comoda_analytics}"
} > "$ML_ENV"
echo "Wrote $ML_ENV"

BACKEND_ENV="$ROOT_DIR/../backend/.env.generated"
{
  echo "# Generated by infra/scripts/generate_env.sh"
  echo "DATABASE_HOST=127.0.0.1"
  echo "DATABASE_NAME=portfolio"
  echo "DATABASE_USER=${DATABASE_USER:-app}"
  echo "DATABASE_PASSWORD=${DATABASE_PASSWORD:-change_me}"
} > "$BACKEND_ENV"
echo "Wrote $BACKEND_ENV"

# Extend to include Cloud Run URLs and Secret names as needed.
